owner: h6rd
repo: Dota2PornFxStatus

sites:
  - name: GitHub
    url: https://h6rd.github.io/Dota2PornFxWeb/
  - name: Vercel
    url: https://d2pfx.vercel.app/
  - name: Netlify
    url: https://d2pfx.netlify.app/
  - name: Render
    url: https://d2pfx.onrender.com/

status-website:
  baseUrl: /Dota2PornFxStatus
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dota2PornFxStatus
  themeUrl: https://cdn.statically.io/gh/h6rd/Dota2PornFxStatus@master/assets/custom.css